function getGif (weather, day) {
  if (weather === 'Thunderstorm') {
    day.classList.remove('cloudy')
    day.classList.remove('rain')
    day.classList.remove('drizzle')
    day.classList.remove('snow')
    day.classList.remove('fog')
    day.classList.remove('ash')
    day.classList.remove('tornado')
    day.classList.remove('dust')
    day.classList.remove('clear')
    day.classList.add('thunder')
  } else if (weather === 'Drizzle') {
    day.classList.add('drizzle')
  } else if (weather === 'Rain') {
    day.classList.remove('cloudy')
    day.classList.remove('thunder')
    day.classList.remove('drizzle')
    day.classList.remove('snow')
    day.classList.remove('fog')
    day.classList.remove('ash')
    day.classList.remove('tornado')
    day.classList.remove('dust')
    day.classList.remove('clear')
    day.classList.add('rain')
  } else if (weather === 'Snow') {
    day.classList.remove('cloudy')
    day.classList.remove('thunder')
    day.classList.remove('drizzle')
    day.classList.remove('rain')
    day.classList.remove('fog')
    day.classList.remove('ash')
    day.classList.remove('tornado')
    day.classList.remove('dust')
    day.classList.remove('clear')
    day.classList.add('snow')
  } else if (weather === 'Fog' || weather === 'Haze' || weather === 'Smoke' || weather === 'Mist') {
    day.classList.remove('cloudy')
    day.classList.remove('thunder')
    day.classList.remove('drizzle')
    day.classList.remove('rain')
    day.classList.remove('snow')
    day.classList.remove('ash')
    day.classList.remove('tornado')
    day.classList.remove('dust')
    day.classList.remove('clear')
    day.classList.add('fog')
  } else if (weather === 'Tornado' || weather === 'Squall') {
    day.classList.add('tornado')
  } else if (weather === 'Ash') {
    day.classList.remove('cloudy')
    day.classList.remove('thunder')
    day.classList.remove('drizzle')
    day.classList.remove('rain')
    day.classList.remove('snow')
    day.classList.remove('fog')
    day.classList.remove('tornado')
    day.classList.remove('dust')
    day.classList.remove('clear')
    day.classList.add('ash')
  } else if (weather === 'Dust' || weather === 'Sand') {
    day.classList.remove('cloudy')
    day.classList.remove('thunder')
    day.classList.remove('drizzle')
    day.classList.remove('rain')
    day.classList.remove('snow')
    day.classList.remove('fog')
    day.classList.remove('tornado')
    day.classList.remove('ash')
    day.classList.remove('clear')
    day.classList.add('dust')
  } else if (weather === 'Clear') {
    day.classList.remove('cloudy')
    day.classList.remove('thunder')
    day.classList.remove('drizzle')
    day.classList.remove('rain')
    day.classList.remove('snow')
    day.classList.remove('fog')
    day.classList.remove('tornado')
    day.classList.remove('ash')
    day.classList.remove('dust')
    day.classList.add('clear')
  } else if (weather === 'Clouds') {
    day.classList.remove('clear')
    day.classList.remove('thunder')
    day.classList.remove('drizzle')
    day.classList.remove('rain')
    day.classList.remove('snow')
    day.classList.remove('fog')
    day.classList.remove('tornado')
    day.classList.remove('ash')
    day.classList.remove('dust')
    day.classList.add('cloudy')
  }
}

export default getGif
